version: '2.4'

services:
  team-tigers:
    image: robocupssl/ubuntu-vnc-java:0.3.1
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
      VNC_RESOLUTION: 1920x1080
    volumes:
      - team-tigers-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-erforce:
    image: roboticserlangen/robocup:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-erforce-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-ubcthunderbots:
    image: ubcthunderbots/tbots-software-env:0.0.1
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-ubcthunderbots-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-robocin:
    image: lhcs/robocin-coach:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-robocin-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-robofei:
    image: bollos00/robofeissl-ssl-strategy:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-robofei-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-roboteamtwente:
    image: yuhanuncitgez/robocup:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-roboteamtwente-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-uroborus:
    image: uroborus/larcmacs:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-uroborus-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole
      
  team-roboime:
    image: roboime/robocup2021:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-roboime-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-robodragons:
    image: sslrobodragons/robodragons-system:ubuntu20.04-robocup2021-simulation-c9440ae
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-robodragons-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-src:
    image: xlq57913/robocup2021-src:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-src-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole
      
  team-kiks:
    image: ghcr.io/kiksworks/ssl-simulation-env:main
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-kiks-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole
  
  team-kgpkubs:
    image: nisarg1631/kgpkubs:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-kgpkubs-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole
  team-omid:
    image: fdmxfarhan/omid:latest
    user: "1000"
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-omid-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole
  

volumes:
  team-tigers-data:
  team-erforce-data:
  team-ubcthunderbots-data:
  team-robocin-data:
  team-robofei-data:
  team-roboteamtwente-data:
  team-uroborus-data:
  team-roboime-data:
  team-robodragons-data:
  team-src-data:
  team-kiks-data:
  team-kgpkubs-data:
  team-omid-data:
  
networks:
  match:
  guacamole:
